### ISSUE TITLE
pynance.data.retrieve.get fails

### ISSUE THREAD

**Issue by mrcartier** [GriffinAustin/pynance#32]
retrieval for US equities (data.equities) works just fine:
>>> eqs = pn.data.equities('US')
>>> print eqs

but for individual equities it fails:
>>> goog = pn.data.get('goog', '2016')
>>> print goog
Empty DataFrame
Columns: [d=document, e=d.documentElement, b=d.body, x=w.innerWidth||e.clientWidth||b.clientWidth, y=w.innerHeight||e.clientHeight||b.clientHeight;url+="&w="+x+"&h="+y;}window.location.replace(url);</script></head><body></body></html>]
Index: []

Any ideas on a workaround? If this is indeed related the pandas-datareader yahoo problem then can we simply call google instead? I'm referencing retrieve.py found [here](https://github.com/aisthesis/pynance/blob/develop/pynance/data/retrieve.py), specifically changing line 34 from 'yahoo' to 'google' but I'm uncertain how that would impact the rest of the package...

**Comment by aisthesis** [comment]
It is the `pandas-datareader` Yahoo! problem. You can certainly use Google rather than yahoo as data source by changing the line you mention. I didn't use Google originally because they didn't provide as much data as Yahoo. If you try that fix, please post how it goes. It might make sense to switch to Google in future versions.

You may also find that `pandas-datareader` has fixed the issue in the most recent version (0.5.0), so the current code might work after all if you update the `pandas-datareader` dependency.

**Comment by mrcartier** [comment]
Thanks, the pandas-datareader update has it working fine. Great package, deserves more stars.
